from __future__ import annotations

from datetime import datetime, timezone

import pytest
from bson import Binary, Code, Int64, MaxKey, MinKey, ObjectId, Regex, Timestamp

from documentdb_tests.compatibility.tests.core.operator.expressions.utils.utils import (
    assert_expression_result,
    execute_expression,
)
from documentdb_tests.framework.error_codes import (
    REPLACE_FIND_TYPE_ERROR,
    REPLACE_INPUT_TYPE_ERROR,
    REPLACE_REPLACEMENT_TYPE_ERROR,
)
from documentdb_tests.framework.parametrize import pytest_params
from documentdb_tests.framework.test_constants import DECIMAL128_ONE_AND_HALF

from .utils.replaceOne_common import (
    ReplaceOneTest,
    _expr,
)

# Property [Type Strictness]: all three parameters must resolve to a string or
# null. Any other type produces an error specific to the argument position.
REPLACEONE_TYPE_ERROR_TESTS: list[ReplaceOneTest] = [
    # Invalid input types.
    ReplaceOneTest(
        "type_input_array",
        input=["a"],
        find="a",
        replacement="b",
        error_code=REPLACE_INPUT_TYPE_ERROR,
        msg="$replaceOne should reject array as input",
    ),
    ReplaceOneTest(
        "type_input_binary",
        input=Binary(b"data"),
        find="a",
        replacement="b",
        error_code=REPLACE_INPUT_TYPE_ERROR,
        msg="$replaceOne should reject binary as input",
    ),
    ReplaceOneTest(
        "type_input_bool",
        input=True,
        find="a",
        replacement="b",
        error_code=REPLACE_INPUT_TYPE_ERROR,
        msg="$replaceOne should reject bool as input",
    ),
    ReplaceOneTest(
        "type_input_date",
        input=datetime(2024, 1, 1, tzinfo=timezone.utc),
        find="a",
        replacement="b",
        error_code=REPLACE_INPUT_TYPE_ERROR,
        msg="$replaceOne should reject date as input",
    ),
    ReplaceOneTest(
        "type_input_decimal128",
        input=DECIMAL128_ONE_AND_HALF,
        find="a",
        replacement="b",
        error_code=REPLACE_INPUT_TYPE_ERROR,
        msg="$replaceOne should reject decimal128 as input",
    ),
    ReplaceOneTest(
        "type_input_float",
        input=3.14,
        find="a",
        replacement="b",
        error_code=REPLACE_INPUT_TYPE_ERROR,
        msg="$replaceOne should reject float as input",
    ),
    ReplaceOneTest(
        "type_input_int",
        input=42,
        find="a",
        replacement="b",
        error_code=REPLACE_INPUT_TYPE_ERROR,
        msg="$replaceOne should reject int as input",
    ),
    ReplaceOneTest(
        "type_input_long",
        input=Int64(42),
        find="a",
        replacement="b",
        error_code=REPLACE_INPUT_TYPE_ERROR,
        msg="$replaceOne should reject long as input",
    ),
    ReplaceOneTest(
        "type_input_maxkey",
        input=MaxKey(),
        find="a",
        replacement="b",
        error_code=REPLACE_INPUT_TYPE_ERROR,
        msg="$replaceOne should reject maxkey as input",
    ),
    ReplaceOneTest(
        "type_input_minkey",
        input=MinKey(),
        find="a",
        replacement="b",
        error_code=REPLACE_INPUT_TYPE_ERROR,
        msg="$replaceOne should reject minkey as input",
    ),
    ReplaceOneTest(
        "type_input_object",
        input={"a": 1},
        find="a",
        replacement="b",
        error_code=REPLACE_INPUT_TYPE_ERROR,
        msg="$replaceOne should reject object as input",
    ),
    ReplaceOneTest(
        "type_input_objectid",
        input=ObjectId("507f1f77bcf86cd799439011"),
        find="a",
        replacement="b",
        error_code=REPLACE_INPUT_TYPE_ERROR,
        msg="$replaceOne should reject objectid as input",
    ),
    ReplaceOneTest(
        "type_input_regex",
        input=Regex("pattern"),
        find="a",
        replacement="b",
        error_code=REPLACE_INPUT_TYPE_ERROR,
        msg="$replaceOne should reject regex as input",
    ),
    ReplaceOneTest(
        "type_input_timestamp",
        input=Timestamp(1, 1),
        find="a",
        replacement="b",
        error_code=REPLACE_INPUT_TYPE_ERROR,
        msg="$replaceOne should reject timestamp as input",
    ),
    ReplaceOneTest(
        "type_input_binary_uuid",
        input=Binary(b"\x00" * 16, subtype=4),
        find="a",
        replacement="b",
        error_code=REPLACE_INPUT_TYPE_ERROR,
        msg="$replaceOne should reject binary uuid as input",
    ),
    ReplaceOneTest(
        "type_input_code",
        input=Code("function(){}"),
        find="a",
        replacement="b",
        error_code=REPLACE_INPUT_TYPE_ERROR,
        msg="$replaceOne should reject code as input",
    ),
    ReplaceOneTest(
        "type_input_code_with_scope",
        input=Code("function(){}", {"x": 1}),
        find="a",
        replacement="b",
        error_code=REPLACE_INPUT_TYPE_ERROR,
        msg="$replaceOne should reject code with scope as input",
    ),
    # Invalid find types.
    ReplaceOneTest(
        "type_find_array",
        input="hello",
        find=["a"],
        replacement="b",
        error_code=REPLACE_FIND_TYPE_ERROR,
        msg="$replaceOne should reject array as find",
    ),
    ReplaceOneTest(
        "type_find_binary",
        input="hello",
        find=Binary(b"data"),
        replacement="b",
        error_code=REPLACE_FIND_TYPE_ERROR,
        msg="$replaceOne should reject binary as find",
    ),
    ReplaceOneTest(
        "type_find_bool",
        input="hello",
        find=True,
        replacement="b",
        error_code=REPLACE_FIND_TYPE_ERROR,
        msg="$replaceOne should reject bool as find",
    ),
    ReplaceOneTest(
        "type_find_date",
        input="hello",
        find=datetime(2024, 1, 1, tzinfo=timezone.utc),
        replacement="b",
        error_code=REPLACE_FIND_TYPE_ERROR,
        msg="$replaceOne should reject date as find",
    ),
    ReplaceOneTest(
        "type_find_decimal128",
        input="hello",
        find=DECIMAL128_ONE_AND_HALF,
        replacement="b",
        error_code=REPLACE_FIND_TYPE_ERROR,
        msg="$replaceOne should reject decimal128 as find",
    ),
    ReplaceOneTest(
        "type_find_float",
        input="hello",
        find=3.14,
        replacement="b",
        error_code=REPLACE_FIND_TYPE_ERROR,
        msg="$replaceOne should reject float as find",
    ),
    ReplaceOneTest(
        "type_find_int",
        input="hello",
        find=42,
        replacement="b",
        error_code=REPLACE_FIND_TYPE_ERROR,
        msg="$replaceOne should reject int as find",
    ),
    ReplaceOneTest(
        "type_find_long",
        input="hello",
        find=Int64(42),
        replacement="b",
        error_code=REPLACE_FIND_TYPE_ERROR,
        msg="$replaceOne should reject long as find",
    ),
    ReplaceOneTest(
        "type_find_maxkey",
        input="hello",
        find=MaxKey(),
        replacement="b",
        error_code=REPLACE_FIND_TYPE_ERROR,
        msg="$replaceOne should reject maxkey as find",
    ),
    ReplaceOneTest(
        "type_find_minkey",
        input="hello",
        find=MinKey(),
        replacement="b",
        error_code=REPLACE_FIND_TYPE_ERROR,
        msg="$replaceOne should reject minkey as find",
    ),
    ReplaceOneTest(
        "type_find_object",
        input="hello",
        find={"a": 1},
        replacement="b",
        error_code=REPLACE_FIND_TYPE_ERROR,
        msg="$replaceOne should reject object as find",
    ),
    ReplaceOneTest(
        "type_find_objectid",
        input="hello",
        find=ObjectId("507f1f77bcf86cd799439011"),
        replacement="b",
        error_code=REPLACE_FIND_TYPE_ERROR,
        msg="$replaceOne should reject objectid as find",
    ),
    ReplaceOneTest(
        "type_find_regex",
        input="hello",
        find=Regex("pattern"),
        replacement="b",
        error_code=REPLACE_FIND_TYPE_ERROR,
        msg="$replaceOne should reject regex as find",
    ),
    ReplaceOneTest(
        "type_find_timestamp",
        input="hello",
        find=Timestamp(1, 1),
        replacement="b",
        error_code=REPLACE_FIND_TYPE_ERROR,
        msg="$replaceOne should reject timestamp as find",
    ),
    ReplaceOneTest(
        "type_find_binary_uuid",
        input="hello",
        find=Binary(b"\x00" * 16, subtype=4),
        replacement="b",
        error_code=REPLACE_FIND_TYPE_ERROR,
        msg="$replaceOne should reject binary uuid as find",
    ),
    ReplaceOneTest(
        "type_find_code",
        input="hello",
        find=Code("function(){}"),
        replacement="b",
        error_code=REPLACE_FIND_TYPE_ERROR,
        msg="$replaceOne should reject code as find",
    ),
    ReplaceOneTest(
        "type_find_code_with_scope",
        input="hello",
        find=Code("function(){}", {"x": 1}),
        replacement="b",
        error_code=REPLACE_FIND_TYPE_ERROR,
        msg="$replaceOne should reject code with scope as find",
    ),
    # Invalid replacement types.
    ReplaceOneTest(
        "type_replacement_array",
        input="hello",
        find="a",
        replacement=["a"],
        error_code=REPLACE_REPLACEMENT_TYPE_ERROR,
        msg="$replaceOne should reject array as replacement",
    ),
    ReplaceOneTest(
        "type_replacement_binary",
        input="hello",
        find="a",
        replacement=Binary(b"data"),
        error_code=REPLACE_REPLACEMENT_TYPE_ERROR,
        msg="$replaceOne should reject binary as replacement",
    ),
    ReplaceOneTest(
        "type_replacement_bool",
        input="hello",
        find="a",
        replacement=True,
        error_code=REPLACE_REPLACEMENT_TYPE_ERROR,
        msg="$replaceOne should reject bool as replacement",
    ),
    ReplaceOneTest(
        "type_replacement_date",
        input="hello",
        find="a",
        replacement=datetime(2024, 1, 1, tzinfo=timezone.utc),
        error_code=REPLACE_REPLACEMENT_TYPE_ERROR,
        msg="$replaceOne should reject date as replacement",
    ),
    ReplaceOneTest(
        "type_replacement_decimal128",
        input="hello",
        find="a",
        replacement=DECIMAL128_ONE_AND_HALF,
        error_code=REPLACE_REPLACEMENT_TYPE_ERROR,
        msg="$replaceOne should reject decimal128 as replacement",
    ),
    ReplaceOneTest(
        "type_replacement_float",
        input="hello",
        find="a",
        replacement=3.14,
        error_code=REPLACE_REPLACEMENT_TYPE_ERROR,
        msg="$replaceOne should reject float as replacement",
    ),
    ReplaceOneTest(
        "type_replacement_int",
        input="hello",
        find="a",
        replacement=42,
        error_code=REPLACE_REPLACEMENT_TYPE_ERROR,
        msg="$replaceOne should reject int as replacement",
    ),
    ReplaceOneTest(
        "type_replacement_long",
        input="hello",
        find="a",
        replacement=Int64(42),
        error_code=REPLACE_REPLACEMENT_TYPE_ERROR,
        msg="$replaceOne should reject long as replacement",
    ),
    ReplaceOneTest(
        "type_replacement_maxkey",
        input="hello",
        find="a",
        replacement=MaxKey(),
        error_code=REPLACE_REPLACEMENT_TYPE_ERROR,
        msg="$replaceOne should reject maxkey as replacement",
    ),
    ReplaceOneTest(
        "type_replacement_minkey",
        input="hello",
        find="a",
        replacement=MinKey(),
        error_code=REPLACE_REPLACEMENT_TYPE_ERROR,
        msg="$replaceOne should reject minkey as replacement",
    ),
    ReplaceOneTest(
        "type_replacement_object",
        input="hello",
        find="a",
        replacement={"a": 1},
        error_code=REPLACE_REPLACEMENT_TYPE_ERROR,
        msg="$replaceOne should reject object as replacement",
    ),
    ReplaceOneTest(
        "type_replacement_objectid",
        input="hello",
        find="a",
        replacement=ObjectId("507f1f77bcf86cd799439011"),
        error_code=REPLACE_REPLACEMENT_TYPE_ERROR,
        msg="$replaceOne should reject objectid as replacement",
    ),
    ReplaceOneTest(
        "type_replacement_regex",
        input="hello",
        find="a",
        replacement=Regex("pattern"),
        error_code=REPLACE_REPLACEMENT_TYPE_ERROR,
        msg="$replaceOne should reject regex as replacement",
    ),
    ReplaceOneTest(
        "type_replacement_timestamp",
        input="hello",
        find="a",
        replacement=Timestamp(1, 1),
        error_code=REPLACE_REPLACEMENT_TYPE_ERROR,
        msg="$replaceOne should reject timestamp as replacement",
    ),
    ReplaceOneTest(
        "type_replacement_binary_uuid",
        input="hello",
        find="a",
        replacement=Binary(b"\x00" * 16, subtype=4),
        error_code=REPLACE_REPLACEMENT_TYPE_ERROR,
        msg="$replaceOne should reject binary uuid as replacement",
    ),
    ReplaceOneTest(
        "type_replacement_code",
        input="hello",
        find="a",
        replacement=Code("function(){}"),
        error_code=REPLACE_REPLACEMENT_TYPE_ERROR,
        msg="$replaceOne should reject code as replacement",
    ),
    ReplaceOneTest(
        "type_replacement_code_with_scope",
        input="hello",
        find="a",
        replacement=Code("function(){}", {"x": 1}),
        error_code=REPLACE_REPLACEMENT_TYPE_ERROR,
        msg="$replaceOne should reject code with scope as replacement",
    ),
]


@pytest.mark.parametrize("test_case", pytest_params(REPLACEONE_TYPE_ERROR_TESTS))
def test_replaceone_type_error_cases(collection, test_case: ReplaceOneTest):
    """Test $replaceOne type error cases."""
    result = execute_expression(collection, _expr(test_case))
    assert_expression_result(
        result,
        expected=test_case.expected,
        error_code=test_case.error_code,
        msg=test_case.msg,
    )
